### PR TITLE
add eslint and lesslint into grunt watch task

### PR DESCRIPTION
**Pull request by haoliangyu**
More code linters! The [grunt-eslint](https://www.npmjs.com/package/grunt-eslint) and [grunt-lesslint](https://www.npmjs.com/package/grunt-lesslint) are added into the grunt watch task. The linter will work first after code change and stop following tasks if any errors is detected. Warnings will be ignored. 

Also some minor issues are fixed after the linters are implemented.

### CODE REVIEW

**Comment by jvgriffis** [comment]
is this actually used anywhere, or just adding the config for future use?

**Comment by haoliangyu** [comment]
We are using the same configuration at vetro.

**Comment by jvgriffis** [comment]
What I mean is, this commit does not appear to actually do anything. It's just a config file and updating package.json to download deps.

Does Gruntfile already run eslint?

**Comment by haoliangyu** [comment]
You are right. This commit only adds the eslint config and I can add it as grunt task if you think that's necessary.

**Pull request merged**
