### PR TITLE
add gulp

### PR DESCRIPTION
**Pull request by haoliangyu**
The gulp workflow is the same as the grunt's, but it's much faster as everything runs in memory and in parallel.

### CODE REVIEW

**Comment by NathanMarq** [comment]
In this case, I would want to push for wider support and have a separate Gulpfile, and keep the Gruntfile. This way it gives an option and won't break the current workflow for anyone.

This would be a similar method as how it's set up with npm scripts also.

Would you mind creating a separate gulpfile for this?

**Comment by haoliangyu** [comment]
@NathanMarq I have restored the Gruntfile and added ES6 support using  `grunt-babel`. BTW, the `testling` task is broken. I don't know how to fix it.

**Comment by haoliangyu** [comment]
Letting three build tools coexist in the repo makes it pretty messy (from my perspective). How do you think moving these configs to `bootstrapping` folder and letting the user to choose one by using some commands?

**Comment by NathanMarq** [comment]
@haoliangyu
I've been planning on doing some "options" like this for angular/other app frameworks also, the only problem is that Vagrant doesn't allow scripts to run interactively when they are provisioning the VM.

The main solution for now I guess would be to have separate scripts for each piece, and have the developer put in the parts they want in the Vagrantfile to be run sequentially when they provision... 

What do you think?

**Comment by haoliangyu** [comment]
I don't think it's a good idea to let the developer modify the Vagrantfile directly. My idea is set up an `options` folder and the Vagrantfile would run everything in the folder at the provision. In this way, the developer will just need to copy and paste the separate scripts into the `options` folder. Furthermore, we may set up a command to trigger `sudo vagrant up` and enable the developer to pick optional components before the provision starts.

**Comment by NathanMarq** [comment]
@haoliangyu We can automate this process... we can probably just run a setup script that asks users to define everything they want to use (before Vagrant provisions). This script can then copy all the files over that it needs to fulfill those choices. As it is right now, we already have the `extras` folder with supplementary install scripts (like Postgres and Lockit)

I'd rather take it a step further into automation because copy-pasting individual files can lead to missing features if the developer doesn't copy all the necessary files...

**Comment by haoliangyu** [comment]
@NathanMarq I agree. I will close this PR now until we finalize the definition of the setup process.

**Pull request closed without merging**
